Fixes a NoClassDefFoundError that caused the Tellstick addon to not work properly
Fixes #7024
The problem was caused by the asynchttpclient dependency that seemed to require another version of the Netty dependency than what is added by the openhab.tp-netty feature.
This caused some of the classes in the ssl package to not be found during initialization.
I fixed it by upgrading the asynchttpclient dependency to a version that use the same version of Netty that is bundled(4.1.42.Final).

Signed-off-by: Jörgen Nilsson <mail.jnilsson@gmail.com>