[homekit] Fix NoClassDefFoundError by adding missing javax.jmdns package import (#5471)
Caused by #4920
Fixes #5432

Signed-off-by: Wouter Born <github@maindrain.net>
Signed-off-by: Pshatsillo <pshatsillo@gmail.com>