[ecovacs] Catch more exceptions when parsing vacuum data
Missing fields in the responses so far went uncaught:

2026-01-08 14:19:31.852 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "resp.waterAmount" is null
	at org.openhab.binding.ecovacs.internal.api.commands.GetMoppingWaterAmountCommand.convertResponse(GetMoppingWaterAmountCommand.java:45) ~[?:?]
	at org.openhab.binding.ecovacs.internal.api.commands.GetMoppingWaterAmountCommand.convertResponse(GetMoppingWaterAmountCommand.java:1) ~[?:?]
	at org.openhab.binding.ecovacs.internal.api.impl.EcovacsApiImpl.sendIotCommand(EcovacsApiImpl.java:308) ~[?:?]
	at org.openhab.binding.ecovacs.internal.api.impl.EcovacsIotMqDevice.sendCommand(EcovacsIotMqDevice.java:98) ~[?:?]
	at org.openhab.binding.ecovacs.internal.handler.EcovacsVacuumHandler.lambda$15(EcovacsVacuumHandler.java:632) ~[?:?]
	at org.openhab.binding.ecovacs.internal.handler.EcovacsVacuumHandler.doWithDevice(EcovacsVacuumHandler.java:822) ~[?:?]
	at org.openhab.binding.ecovacs.internal.handler.EcovacsVacuumHandler.pollData(EcovacsVacuumHandler.java:591) ~[?:?]
	at org.openhab.binding.ecovacs.internal.api.util.SchedulerTask.run(SchedulerTask.java:95) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]

Make sure to catch those and make the user aware of it by setting the
thing to offline / communication error instead of just emitting a
warning in the log, so they get a chance to report that problem. With
the previous behavior everything apparently was OK, but channels were
not populated correctly.

Signed-off-by: Danny Baumann <dannybaumann@web.de>