Update temperaturehumidity.xml
exception in log:
Exception occured while informing handler:Unknown packet type
TEMPERATUREHUMIDITY
java.lang.IllegalArgumentException: Unknown packet type
TEMPERATUREHUMIDITY
        at
org.openhab.binding.rfxcom.internal.messages.RFXComMessageFactory.convertPacketType(RFXComMessageFactory.java:143)[198:org.openhab.binding.rfxcom:2.0.0.201610211435]
        
Problem caused by different names in xml and java (underscore missing)
Tested with TH7, TFA TS34C, Cresta type.
There is similar problem with temperature_humidity_barometric but i
can't find xml file in ESH-INF and don't have sensor to test.

Signed-off-by: Zahari Zahariev <harryzz@gmail.com>