Fix IllegalArgumentExceptions in SysteminfoOSGiTest (#3716)
The tests started throwing the following IAE due to changes in https://github.com/eclipse/smarthome/pull/5838:

java.lang.IllegalArgumentException: The given reference (class: class org.openhab.binding.systeminfo.internal.discovery.SysteminfoDiscoveryService) does not implement an interface.
	at org.eclipse.smarthome.test.java.JavaOSGiTest.getInterfaceName(JavaOSGiTest.java:289)
	at org.eclipse.smarthome.test.java.JavaOSGiTest.unregisterService(JavaOSGiTest.java:258)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testDiscoveryService(SysteminfoOSGiTest.java:922)
	at org.openhab.binding.systeminfo.test.SysteminfoOSGiTest.testDiscoveryWithUnresolvedHostname(SysteminfoOSGiTest.java:904)

Signed-off-by: Wouter Born <eclipse@maindrain.net>