[homekit] Fix NoClassDefFoundError by adding missing javax.jmdns package import
Caused by #4920
Fixes #5432

Signed-off-by: Wouter Born <github@maindrain.net>